deploy_tasks:
  development:
    before_deploy:
      - npm install gitbook-cli
      - node ./node_modules/gitbook-cli/bin/gitbook.js -v 2.6.7 fetch
      - node ./node_modules/gitbook-cli/bin/gitbook.js -v 2.6.7 install
      - node ./node_modules/gitbook-cli/bin/gitbook.js -v 2.6.7 build
